version: "2"
services:

# Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

# Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.79.0
    command: ["--config=/etc/otel-config.yaml", ""]
    volumes:
      - ./otel-config.yaml:/etc/otel-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one

